#pragma once
#define  _CRT_SECURE_NO_WARNINGS
#include <iostream>
#include <string>
#include <vector>
#include <io.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <Windows.h>
#include <stdarg.h>
#include <thread>
#include <sstream>
#include <shared_mutex>
#include <mutex>
#define __DEBUG__
#define __TRACE__
using std::cout;
using std::endl;
using std::vector;
using std::string;